version: '3'
services:

  placemats:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
      - NCBI_EMAIL=ncbi.dev.robot.user@gmail.com

  mongodb:
    image: mongo:3.6
    ports:
      - "27017"
